using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApp.Models
{
    /// <summary>
    /// Tracks a single occupancy session from ENTRY to EXIT.
    /// Every RFID-authenticated entry creates exactly ONE session.
    /// All subsequent events (loitering, PIR updates) reference this SessionId.
    /// This is the core anti-duplication mechanism.
    /// </summary>
    [Table("occupancy_sessions")]
    public class OccupancySession
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }

        // =========================
        // SESSION IDENTITY
        // =========================

        /// <summary>
        /// Unique session ID generated by the Python edge controller (UUID).
        /// All subsequent state transitions reference this ID.
        /// </summary>
        [Required]
        [Column("session_id")]
        [StringLength(50)]
        public string SessionId { get; set; } = string.Empty;

        /// <summary>
        /// The authorized person who entered.
        /// </summary>
        [Column("person_id")]
        public int? PersonId { get; set; }

        [ForeignKey("PersonId")]
        public AuthorizedPersonnel? Person { get; set; }

        /// <summary>
        /// Room being occupied.
        /// </summary>
        [Column("room_id")]
        public int? RoomId { get; set; }

        [ForeignKey("RoomId")]
        public Room? Room { get; set; }

        // =========================
        // TIMESTAMPS
        // =========================

        /// <summary>
        /// When the person entered (RFID + Face verified).
        /// Set exactly ONCE on session creation.
        /// </summary>
        [Required]
        [Column("entry_time")]
        public DateTime EntryTime { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// When the person exited. NULL means still inside.
        /// </summary>
        [Column("exit_time")]
        public DateTime? ExitTime { get; set; }

        // =========================
        // STATE TRACKING
        // =========================

        /// <summary>
        /// Current session status:
        /// INSIDE — person is verified and present
        /// LOITERING — prolonged inactivity detected
        /// COMPLETED — exited normally
        /// EXPIRED — inactivity inference exit (soft exit)
        /// </summary>
        [Required]
        [Column("status")]
        [StringLength(20)]
        public string Status { get; set; } = "INSIDE";

        /// <summary>
        /// How the exit was determined:
        /// DOOR_SENSOR — magnetic door sensor (highest priority, future)
        /// RFID_EXIT — re-tapped RFID to exit
        /// INFERENCE — inactivity timeout (fallback only)
        /// null — still inside
        /// </summary>
        [Column("exit_reason")]
        [StringLength(20)]
        public string? ExitReason { get; set; }

        /// <summary>
        /// Face verification confidence at entry (0.0 to 1.0).
        /// Stored for audit trail.
        /// </summary>
        [Column("face_confidence")]
        public float? FaceConfidence { get; set; }

        /// <summary>
        /// RFID UID used for this session.
        /// </summary>
        [Column("rfid_uid")]
        [StringLength(50)]
        public string? RfidUid { get; set; }

        // =========================
        // UI HELPERS (NOT IN DB)
        // =========================

        [NotMapped]
        public bool IsActive => ExitTime == null;

        [NotMapped]
        public string PersonName => Person?.FullName ?? "Unknown";

        [NotMapped]
        public string RoomName => Room?.RoomName ?? "Unknown";

        [NotMapped]
        public double MinutesInside =>
            ExitTime.HasValue
                ? (ExitTime.Value - EntryTime).TotalMinutes
                : (DateTime.UtcNow - EntryTime).TotalMinutes;
    }
}
